import TopNav from "@/components/TopNav";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <main className="bg-black w-screen h-screen overflow-hidden select-none">
          <TopNav />
          <div className="p-4 h-screen overflow-y-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}
