import { cls } from "@/lib/class-name";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Kim YoungJin Portfolio Page",
  description: "Generated by Next.js",
};

const font = Noto_Sans_KR({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const className = cls(
    "w-full h-full select-none leading-tight",
    font.className
  );

  return (
    <html lang="ko">
      <body>
        <main className={className}>{children}</main>
      </body>
    </html>
  );
}
